destination: public
exclude: [Makefile, Gemfile, Gemfile.lock, .rvmrc, public, sample-code]
splash: false
splash_homepage: false
root: /nasa-dev.socrata.com

subsite: dev
title: NASA Developers
icon: fa fa-code
github_repo: https://github.com/socrata/nasa-dev.socrata.com
contribute: /contributing.html

local_js:
  - /js/purl.js
  - /js/try.js
  - /js/github.js

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions
