destination: public
exclude: [Makefile, Gemfile, Gemfile.lock, .rvmrc, public, sample-code]
splash: false
splash_homepage: false

subsite: dev
title: NASA Developers
icon: fa fa-code
github_repo: https://github.com/socrata/nasa-dev.socrata.com
contribute: /contributing.html

local_js:
  - //cdnjs.cloudflare.com/ajax/libs/mustache.js/0.8.1/mustache.min.js
  - /js/purl.js
  - /js/try.js
  - /js/snufflupadata.js
  - /js/github.js

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions
